image: docker:git

pipelines:
  default:
     - step:
         services:
           - docker
         script:
           - apk add --update bash coreutils tar curl
           - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
           - .industrial_ci/bitbucket.sh ROS_DISTRO=noetic

definitions:
  services:
    docker:
      memory: 2048